### ISSUE TITLE
Remove underscores from variant/consequences ?

### ISSUE THREAD

**Issue by inutano** [dbcls/togosite#16]
togosite の Variant, Consequences の bar の表示ラベル中に `intron_variant` のようにアンダースコアが含まれている。表示するためのラベルなのでアンスコは削除するほうがよさそうです。
https://integbio.jp/togosite/sparqlist/variant_consequence

**Comment by mitsuhashi** [comment]
対応しました。ご確認ください。
https://integbio.jp/togosite/sparqlist/api/variant_consequence?categoryIds=SO_0001060&queryIds=&mode=

**Comment by inutano** [comment]
確認しました！ありがとうございます！
