### ISSUE TITLE
template: disease

### ISSUE THREAD

**Issue by inutano** [dbcls/togosite#31]
hpo/mesh/mondo/nando の template を cat しております:
https://github.com/dbcls/togosite/blob/metastanza-per-subject/config/togosite-human/templates/disease.hbs

`data-url` の SPARQList を1つに統一して以下のようにしてもらえますか 🙇‍♂️ 
- disease 関連 ID のどれが来ても対応できるようにする
  - SPARQList内部でのid変換にはtogosite SPARQLエンドポイントを使用
- SPARQList 内部でそれぞれのDBから情報を取ってマージしたものを表示するためのデータを返す

**Comment by inutano** [comment]
ここで作業中 https://integbio.jp/togosite/sparqlist/test_disease_template_2

todo:
  - 入力されたIDを別ID typeに変換する部分 (`togoid` の sparql のとこ) @TerueTakatsuki 
  - `togoidDict` の javascript @inutano 
  - `main` の select 文で変数がかぶらないように修正する
  - SELECT で hash-table に表示するべき項目を返す

**Comment by mitsuhashi** [comment]
@inutano @TerueTakatsuki  今から作業します。遅くなってすみません。
 https://integbio.jp/togosite/sparqlist/test_disease_template_2
をforkしてから編集します。

**Comment by inutano** [comment]
@mitsuhashi ありがとうございます！不明点あればお知らせください！

**Comment by inutano** [comment]
入力IDを他DBのIDに変換したのち sparql の結果をよしなに object にする `togoidDict` の部分、それっぽい js を書きました、多分動く（はず）
https://integbio.jp/togosite/sparqlist/test_disease_template_2

こんな感じ:

```
({main}) => {
  return main.results.bindings.reduce(
    (obj, elem) => {
      for (const [key, node] of Object.entries(elem)) {
        if (!obj[key]) obj[key] = [];
        obj[key].push(node.value);
      };
      return obj;
    }, {}
  );
}
```
