### ISSUE TITLE
template: proteinStructure

### ISSUE THREAD

**Issue by inutano** [dbcls/togosite#35]
PDBのものを rename しました:
https://github.com/dbcls/togosite/blob/metastanza-per-subject/config/togosite-human/templates/proteinStructure.hbs

Protein Structure の properties の中には uniprot を primaryKey として使うものがあるため、data-url で使っている SPARQList が uniprot ID も受け取れるように修正お願いしたいです。内部でのID変換には togosite エンドポイントを使って、PDBエントリの情報を出力できるとよいかとおもいます。よろしくおねがいします 🙇 

cc. @takaitakai7

**Comment by takaitakai7** [comment]
pdb/uniprotを受け取り、結果を返ってくるところまでSPAQListを修正。
ただし、uniprotのIDに対して、PDBのidが複数存在しているので、複数の値が返ってきている。

**Comment by inutano** [comment]
複数の値が返る部分、どのように表示するか全体の方針をまとめる必要がありそうですね。次回全体会議での論点とさせてください。作業ありがとうございます！

**Comment by yatsuzuka-nbdc** [comment]
Uniprot/PDBいずれかのIDも受け付けて、Uniprot/PDB両方のエントリ内容を返すSparqlistを作成しました。
http://integbio.jp/togosite/sparqlist/test_protein_id
ただし、IDの対応が1対Nになっているので、全件そのまま返しています。
