### ISSUE TITLE
template: variant

### ISSUE THREAD

**Issue by inutano** [dbcls/togosite#36]
togovar の template を rename しています:
https://github.com/dbcls/togosite/blob/metastanza-per-subject/config/togosite-human/templates/variant.hbs

今の所 variant の properties は togovar ID しか使っていないのでこのままでもよさそうかな…？もし今後 property を追加して別の variant ID を使うということであれば変更の必要があるかもです、ご確認ください〜（でもそうしたらなんのためのtogovarだよという話になりそうな気もする）

**Comment by mitsuhashi** [comment]
当面別のvariant IDを使う予定はありませんのでこのままでOKです。
> もし今後 property を追加して別の variant ID を使うということであれば変更の必要があるかもです、ご確認ください〜

バリアントに付与されているIDの最大集合はdbSNP rsIDで6億以上あります。RDF化もしていないし、データ管理も大変な量かと思っています。質の問題もあると思っています。
> Scope
> dbSNP only assigned RefSNP for human organisms as an outcome of the recent collaborations with EMBL-EBI European Variation Archive (EVA). dbSNP Build 152 (November 2018) contains more than 650 million human RefSNP records, of which over 580 million records have population frequency data.

一方、TogoVarは主に日本人由来のデータセットのバリアントだけにIDをつけているので１億程度です。

**Comment by inutano** [comment]
なるほど、了解しました。そうすると togovar の ID 一本のままでよさそうですが、それとは別に togosite で検索できる variant の情報は日本人由来データセットのものであり dbSNP に載っているものが全てあるわけではない、というのがユーザにきちんと伝わる必要がありまそうですね。
