### ISSUE TITLE
gene.hbsのタイポ？

### ISSUE THREAD

**Issue by yucca-t-k** [dbcls/togosite#39]
gene.hbsの中に
`https://integbio.jp/togosite/sparqlist/api/togosite-transcript-summary-ensembl={{id}}`
という行があって
`https://integbio.jp/togosite/sparqlist/api/togosite-transcript-summary-ensembl=ENSG00000010404`
とブラウザから直接入力するとNotFoundといわれます

同じファイルで他にSPARQListを参照しているところは
`https://integbio.jp/togosite/sparqlist/api/togosite-gene-summary-ensembl?ensg={{id}}`
みたいな感じで
`https://integbio.jp/togosite/sparqlist/api/togosite-gene-summary-ensembl?ensg=ENSG00000010404`
とブラウザから直接入力するとJSONでデータが返ってきます。

**Comment by ktym** [comment]
これは昨日 @yucca-t-k さんも出ていた夕方の会議ですでに議題にしています。もちろんURLが間違っているのですが、 @sh-ikeda さんがトランスクリプト用の新しいSPARQListを作られているということでしたので、二度手間ということで修正せずに置いています。

**Comment by yucca-t-k** [comment]
@ktym ご指摘ありがとうございます。聞き逃していたようですみません。いったんCloseします。
